### PR TITLE
Reverse examples/plugin dependency relationship.

### PR DESCRIPTION
**Pull request by sellout**
This moves tests that depend on the plugin from concat-examples to
concat-plugin. The one shortcoming, IMO, is that it requries duplicating
the SMT flag.

### CODE REVIEW

**Comment by sellout** [comment]
It would be helpful for us to have this change in.

**Comment by mikesperber** [comment]
This looks good to me. @conal, any objection to us merging this one?

**Comment by mikesperber** [comment]
Just rebased & merged it.

**Comment by conal** [comment]
Sorry I forgot about this one.

Do all of the examples still build and work, including graphics (WebGL) and SMT?

**Comment by mikesperber** [comment]
So `graphics` builds, and test suites run. `SMT` compiles - is there a test suite or example for that one?

**Comment by mikesperber** [comment]
(I.e. @conal, I see the comment about this in the `README`, but don't see what exactly I should uncomment in `Test/Examples.hs`.)

**Comment by conal** [comment]
@mikesperber Thanks. I don't remember how to test SMT, and I'm happy to assume that it'll work out fine (or doesn't matter).

**Pull request closed without merging**
