### PR TITLE
Zap some obsolete nix files

### PR DESCRIPTION
**Pull request by kenranunderscore**
We've just switched to using the flake, and AFAIK we were the only ones using the previous nix files. Those have also become slightly incompatible over time.
(Let me know if you still need them @sellout, then I'll close this. I've not found any usage in the remaining nix files.)

### CODE REVIEW

**Comment by sellout** [comment]
This is great – I’ve confused myself a couple times with those files.

I think the only thing still used from that era is netlist-overlay.nix, which you’ve left alone. I’m pretty sure the style of that already matches the flake, so seems like this cleans up everything nicely.

Considering the non-flake files aren’t tested or anything (and apparently no longer working, as you say), I think it’s good to go once the build succeeds. We can revert (and fix) if it turns out there are still users out there.

Any thoughts, @mikesperber?

**Review by sellout — APPROVED** [review]
See previous comment.

**Comment by mikesperber** [comment]
> Any thoughts, @mikesperber?

@sellout No - I defer to @kenranunderscore on matters Nix, but we've discussed those changes.

OK to merge?

**Comment by sellout** [comment]
Arg – I just noticed that master has also had a failing build since the flake got merged.

I doubt this change has had any effect on the failures, but if one of you could spot-check it against master’s failures before merging, that’d be great. Otherwise I can in a couple hours … and then I’ll get the failing checks passing after this is merged (and probably mark some checks as required).

**Comment by kenranunderscore** [comment]
I checked 2 or 3 jobs against the currently known failures (divergence between `nix build` and `cabal builds` in golden tests; broken `concat-hardware`) and they seemed to match, but I wasn't very thorough. I can check more of them tomorrow. There are some I don't know well that took very long but that's probably due to everything having to be rebuilt.

**Comment by sellout** [comment]
Ah yeah, now that you mention it, I remember this coming up when we added the flake: https://github.com/compiling-to-categories/concat/pull/111#discussion_r1122078378

I think this is good.

**Comment by sellout** [comment]
Ok, I protected the master branch, added required checks (which is a pain to do, but hopefully I only selected ones that are currently passing).

@mikesperber – feel free to remove restrictions if they’re too much. I tried to leave it pretty open.

And I’d love to enable the merge queue, but I want to have a better sense of it first.

**Pull request merged**
